version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.11
    pre_build:
        commands:
            - echo "Installing dependencies..."
            - pip install -r requirements.txt
    build:
        commands:
#            - echo "Running tests..."
#            - python -m unittest discover tests
            - echo "Building SAM application..."
            - sam build

artifacts:
    files:
        - template.yaml
        - .aws-sam/**/*
    discard-paths: yes
