version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "******** Running SAM Build ********"
      - sam build
      - echo "******** Running SAM Package ********"
      - sam package --output-template-file packaged.yaml --s3-bucket imbilalx-demo

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
