version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "******** Running SAM Build ********"
      - sam build

artifacts:
  files:
    - template.yaml
    - .aws-sam/build/*
  discard-paths: yes
