AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Web Scarping Project for LightHouseCPT

Globals:
  Function:
    Timeout: 30

Resources:
  SamDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
