AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  School Web Scraping Project for LightHouseCPT

Globals:
  Function:
    Timeout: 30

Resources:
  SchoolScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WebScrapingProject/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
