AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  School Web Scraping Project for LightHouseCPT

Globals:
  Function:
    Timeout: 900

Resources:
  SchoolScraper:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SchoolScraperFunction
      CodeUri: SchoolScrapingProject/
      Handler: app.lambda_handler
      Runtime: python3.11
      Role: arn:aws:iam::654654270857:role/School-Scraper-Role
      Architectures:
      - x86_64

  Translator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TranslatorFunction
      CodeUri: TranslatorProject/
      Handler: app2.lambda_handler
      Runtime: python3.11
      Role: arn:aws:iam::654654270857:role/School-Scraper-Role
      Architectures:
        - x86_64

