AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  this is just a demo lambda

Globals:
  Function:
    Timeout: 30

Resources:
  SamDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam_tutorial_demo/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Layers:
      - arn:aws:lambda:us-west-1:336392948345:layer:AWSSDKPandas-Python311:11